### PR TITLE
20 clip creation

### PR DESCRIPTION
**Pull request by bkuen**
- Fix black screen videos on episode videos
- Add custom video render to render trajectories

### CODE REVIEW

**Comment by Wizzardexe** [comment]
The implementation of the VideoRecorder class is functional and well-structured, providing a clear mechanism to replay trajectories from the replay buffer and record them as videos. However, the current approach has a significant performance bottleneck due to storing all rendered frames in memory before writing the video using imageio. Consider replaceing imageio.mimsave with a streaming writer like cv2.VideoWriter or RecordVideoV0 in the VideoRecorder class.

**Comment by jualat** [comment]
I would like to add for documentation purposes that on Linux systems it may be necessary to run the script with `xvfb-run` or `xwfb-run`, e.g. `xvfb -run -- python sac_rlhf.py   --env-id Hopper-v4`

**Comment by bkuen** [comment]
> The implementation of the VideoRecorder class is functional and well-structured, providing a clear mechanism to replay trajectories from the replay buffer and record them as videos. However, the current approach has a significant performance bottleneck due to storing all rendered frames in memory before writing the video using imageio. Consider replaceing imageio.mimsave with a streaming writer like cv2.VideoWriter or RecordVideoV0 in the VideoRecorder class.

As the image are quite simple (at least for now), I don't think the bottleneck would have been to significant. But it was quite easy to change the implementation, so I replaced imageio.mimsave with cv2.VideoWriter anyway. Thus, we now shouldn't run into any issues in any case. Thanks for this note.

**Comment by bkuen** [comment]
> I would like to add for documentation purposes that on Linux systems it may be necessary to run the script with `xvfb-run` or `xwfb-run`, e.g. `xvfb-run -- python sac_rlhf.py --env-id Hopper-v4`

I added a README.md file documenting how to start the script inside a headless Linux environment.

**Review by Wizzardexe — APPROVED** [review]

**Pull request merged**
