### PR TITLE
16: Enhance the rewardnet

### PR DESCRIPTION
**Pull request by jualat**
**Issue:** #16

**What?**
- enhance the reward network

**How?**
- parametrize reward network
- make ensemble
- test for best hyperparameters
- Playing around with many, many hyperparameters and trying to find the best :sweat_smile: 

The cyan line is the current state, heavily smoothed. I assume that adding advanced sampling based on the ensemble increases the reward even more.
image

**Ready to merge to main?**
- [x] Linter passes
- [x] PR Approved

### CODE REVIEW

**Comment by jualat** [comment]
it seems like I'm the first one who needs to lint here, please don't wonder

**Review by flyingpalli — CHANGES_REQUESTED** [review]
Looks really nice, the results are very promising as well!

I am only wondering about some differences compared to pebble, are those by design? If not, maybe we could try to adapt here:

- pebble uses three layers and hidden_dim 256
- pebble applies tanh to the output of the rewardnet

**Comment by jualat** [comment]
> Looks really nice, the results are very promising as well!
> 
> I am only wondering about some differences compared to pebble, are those by design? If not, maybe we could try to adapt here:
> 
>     * pebble uses three layers and hidden_dim 256
> 
>     * pebble applies tanh to the output of the rewardnet

Thanks!

I experimented with a `hidden_dim` of 256 and got the same performance as with `hidden_dim=128` and at the same time much higher memory use.  With 4 layers the model even crashed on my computer because of lack of memory, so I decided to use `hidden_dim=128`, this should work on all of our computers as far as I know.

tanh is actually applied a bit hidden by `reward_net.append(nn.Tanh())`

**Review by flyingpalli — APPROVED** [review]
That's on me, sorry. But really nice implementation then!
I'm still not 100% convinced about the dimension but we can handle this another time.

**Pull request merged**
