### PR TITLE
1: add pre-commit with default black config

### PR DESCRIPTION
**Pull request by flyingpalli**

### CODE REVIEW

**Review by jualat — COMMENTED** [review]
Looks good to me. I think both poetry files here can just be removed or need to be adapted to the ones currently in main to resolve the merge conflict.

We should also think about some automation (GitHub action) for `pre-commit`, so that only correctly linted code can be merged into main.

**Comment by flyingpalli** [comment]
The poetry files have been adapted. I added one file to `.gitignore` but that shouldn't matter (or at least I hope so).

According to my research (but I'm really not sure), adding the flag `--allow-missing-config` at pre-commit installation allows to commit with missing 'pre-comit' config-file when not in the main branch (see [this](https://github.com/pre-commit/pre-commit/issues/984) issue)

**Comment by jualat** [comment]
> According to my research (but I'm really not sure), adding the flag `--allow-missing-config` at pre-commit installation allows to commit with missing 'pre-comit' config-file when not in the main branch.

Looks good to me, but I would prefer using GitHub Actions in combination with status checks to enforce a successfull `pre-commit` run before merging to main

**Comment by flyingpalli** [comment]
> Looks good to me, but I would prefer using [GitHub Actions](https://docs.github.com/en/actions) in combination with [status checks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks) to enforce a successfull `pre-commit` run before merging to main

Makes absolute sense! I think I have no rights to enforce checks, though. Could you check that please?

**Review by jualat — APPROVED** [review]
I added the pre-commit.yml, this gets automatically checked by GitHub

**Comment by jualat** [comment]
I think the problem was that I commited into your branch, you will probably need someone else's approval

**Review by Wizzardexe — APPROVED** [review]

**Comment by jualat** [comment]
This branch was broken somehow, I merged main now

**Review by jualat — APPROVED** [review]

**Pull request merged**
